version: '3.8'

services:
  graphql-api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    command: yarn dev
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/graphql', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
